# Generated by Django 4.0.5 on 2022-06-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_article_basket_category_teacher_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
