# Generated by Django 4.0.5 on 2022-06-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('BR', 'Being Processed'), ('A', 'Accepted'), ('R', 'Rejected')], max_length=20, null=True),
        ),
    ]
