# Generated by Django 4.0.5 on 2022-06-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_request_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('BR', 'Being Processed'), ('A', 'Accepted'), ('R', 'Rejected')], default='BR', max_length=20, null=True),
        ),
    ]
