# Generated by Django 4.0.5 on 2022-06-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_request_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='acticle',
            new_name='article',
        ),
    ]
