# Generated by Django 4.0.5 on 2022-06-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_acticle_request_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='observation',
            field=models.TextField(default='', null=True),
        ),
    ]
