# Generated by Django 4.0.5 on 2022-06-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='myUser',
        ),
    ]
