# Generated by Django 4.0.5 on 2022-06-21 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_profile_alter_article_description_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket_state',
            field=models.CharField(choices=[('BP', 'Being Proccessed'), ('P', 'Processed')], default='BP', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.basket'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
